apps/website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from apps.website import views 

urlpatterns = [
    url(r'^$', cache_page(60 * 15)(views.Home.as_view()), name='home'),
    url(r'^sobre/$', cache_page(60 * 15)(views.Sobre.as_view()), name='sobre'),
    url(r'^doar/$', views.Doacao.as_view(), name='doar'),
    url(r'^galeria/(?P<pk>\d+)/$', cache_page(60 * 15)(views.Galeria.as_view()), name='galeria'),
    url(r'^galeria/lista/$', cache_page(60 * 15)(views.ListaGaleria.as_view()), name='galeria-lista'),
    url(r'^noticia/(?P<pk>\d+)/$', views.Noticia.as_view(), name='noticia'),
    url(r'^noticia/lista/$', views.ListaNoticias.as_view(), name='noticia-lista'),
    url(r'^contato/$', views.Contato.as_view(), name='contato'),
]

estacaocedro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap, index
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf import settings
from .sitemaps import *

sitemaps = {
	'static':StaticViewSitemap,
	'noticia':NoticiaSitemap,
	'galeria':GaleriaSitemap
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sitemap\.xml$', index, {'sitemaps':sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file"),
    url(r'^', include('apps.website.urls', namespace='website')),
    url(r'^painel/', include('apps.painel.urls', namespace='painel')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/website/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone

class Contato(models.Model):
    nome = models.CharField(max_length=100, verbose_name='Nome')
    email = models.EmailField(max_length=100,  blank=True, null=True, verbose_name='E-mail')
    telefone = models.CharField(max_length=20,  blank=True, null=True, verbose_name='Telefone')
    descricao = models.CharField(max_length=255,  blank=True, null=True, verbose_name='Descrição')
    is_visualizada = models.BooleanField(default=False, verbose_name='Visualizada ?')
    data = models.DateTimeField(default=timezone.now, verbose_name='Data')
    class Meta:
        verbose_name_plural = 'Contatos'

    def __str__(self):
        return self.nome


class Doacao(models.Model):

    MODALIDADE_CHOICES = (
        ('1', 'Boleto bancário'),
        ('2', 'Pagamento em Espécie'),
        ('3', 'Depósito bancário'),
        ('4', 'Débito automático')
    )

    nome = models.CharField(max_length=100, verbose_name='Nome')
    rg = models.CharField(max_length=12, verbose_name='RG')
    cpf = models.CharField(max_length=14, verbose_name='CPF')
    email = models.EmailField(max_length=100, verbose_name='E-mail')
    telefone = models.CharField(max_length=20,  blank=True, null=True, verbose_name='Telefone Residencial')
    celular = models.CharField(max_length=21,  blank=True, null=True, verbose_name='Telefone Celular')
    cep = models.CharField(max_length=10, blank=True, null=True, verbose_name='CEP')
    rua = models.CharField(max_length=255, verbose_name='Rua')
    bairro = models.CharField(max_length=50,verbose_name='Bairro')
    cidade = models.CharField(max_length=50, verbose_name='Cidade')
    estado = models.CharField(max_length=2, verbose_name='UF')
    is_visualizada = models.BooleanField(default=False, verbose_name='Visualizada ?')
    data = models.DateTimeField(default=timezone.now, verbose_name='Data')
    valor = models.CharField(max_length=255, verbose_name='Valor doado mensalmente')
    modalidade = models.CharField(max_length=20,  verbose_name='Modalidade de Pagamento', choices=MODALIDADE_CHOICES)

    # CAMPOS OPCIONAIS
    banco = models.CharField(max_length=100, blank=True, null=True, verbose_name='Banco')
    conta  = models.CharField(max_length=20, blank=True, null=True, verbose_name='Conta')
    agencia  = models.CharField(max_length=10, blank=True, null=True, verbose_name='Agência')
    titular  = models.CharField(max_length=100, blank=True, null=True, verbose_name='Titular')
    cpf_cnpj  = models.CharField(max_length=30, blank=True, null=True, verbose_name='CPF/CNPJ')
    class Meta:
        verbose_name_plural = 'Doações'

    def __str__(self):
        return self.nome

apps/website/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Contato, Doacao 

class ContatoForm(forms.ModelForm):
    class Meta:
        model = Contato
        fields = ['nome', 'email', 'telefone', 'descricao']

    def __init__(self, *args, **kwargs):
        super(ContatoForm, self).__init__(*args, **kwargs)
        
        self.fields['nome'].widget.attrs['class'] = 'form-control'
        self.fields['nome'].widget.attrs['data-validation'] = '[NOTEMPTY]'
        self.fields['nome'].widget.attrs['placeholder'] = 'Nome'

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'E-mail'

        self.fields['telefone'].widget.attrs['class'] = 'form-control celular'
        self.fields['telefone'].widget.attrs['placeholder'] = 'Telefone'
        self.fields['telefone'].widget.attrs['data-validation'] = '[NOTEMPTY]'

        self.fields['descricao'].widget.attrs['class'] = 'form-control'
        self.fields['descricao'].widget.attrs['placeholder'] = 'Mensagem'

        
class DoacaoForm(forms.ModelForm):

    class Meta:
        model = Doacao
        fields = ['nome', 'rg', 'cpf', 'email', 'telefone', 'celular', 'cep', 'rua', 
            'bairro', 'cidade', 'estado', 'valor', 'modalidade', 'banco', 'conta', 
            'agencia', 'titular', 'cpf_cnpj']

    def __init__(self, *args, **kwargs):
        super(DoacaoForm, self).__init__(*args, **kwargs)
        
        self.fields['nome'].widget.attrs['class'] = 'form-control'
        self.fields['nome'].widget.attrs['data-validation'] = '[NOTEMPTY]'
        self.fields['nome'].widget.attrs['placeholder'] = 'Nome'

        self.fields['rg'].widget.attrs['class'] = 'form-control'
        self.fields['rg'].widget.attrs['data-validation'] = '[NOTEMPTY]'
        self.fields['rg'].widget.attrs['placeholder'] = 'RG'

        self.fields['cpf'].widget.attrs['class'] = 'form-control cpf'
        self.fields['cpf'].widget.attrs['data-validation'] = '[NOTEMPTY]'
        self.fields['cpf'].widget.attrs['placeholder'] = 'CPF'

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['data-validation'] = '[NOTEMPTY]'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'

        self.fields['telefone'].widget.attrs['class'] = 'form-control telefone'
        self.fields['telefone'].widget.attrs['placeholder'] = 'Telefone Fixo'

        self.fields['celular'].widget.attrs['class'] = 'form-control celular'
        self.fields['celular'].widget.attrs['placeholder'] = 'Telefone Celular'

        self.fields['cep'].widget.attrs['class'] = 'form-control cep'
        self.fields['cep'].widget.attrs['placeholder'] = 'CEP'
        
        self.fields['rua'].widget.attrs['class'] = 'form-control'
        self.fields['rua'].widget.attrs['data-validation'] = '[NOTEMPTY]'
        self.fields['rua'].widget.attrs['placeholder'] = 'Endereço'

        self.fields['bairro'].widget.attrs['class'] = 'form-control'
        self.fields['bairro'].widget.attrs['data-validation'] = '[NOTEMPTY]'
        self.fields['bairro'].widget.attrs['placeholder'] = 'Bairro'

        self.fields['cidade'].widget.attrs['class'] = 'form-control'
        self.fields['cidade'].widget.attrs['data-validation'] = '[NOTEMPTY]'
        self.fields['cidade'].widget.attrs['placeholder'] = 'Cidade'
        
        self.fields['estado'].widget.attrs['class'] = 'form-control'
        self.fields['estado'].widget.attrs['data-validation'] = '[NOTEMPTY]'
        self.fields['estado'].widget.attrs['placeholder'] = 'UF'

        self.fields['valor'].widget.attrs['class'] = 'form-control dinheiro'
        self.fields['valor'].widget.attrs['data-validation'] = '[NOTEMPTY]'
        self.fields['valor'].widget.attrs['placeholder'] = 'Valor (R$)'

        self.fields['modalidade'].widget.attrs['class'] = 'form-control'
        self.fields['modalidade'].widget.attrs['data-validation'] = '[NOTEMPTY]'

        # OPCIONAIS

        self.fields['banco'].widget.attrs['class'] = 'form-control'
        self.fields['banco'].widget.attrs['placeholder'] = 'Banco'
        
        self.fields['conta'].widget.attrs['class'] = 'form-control'
        self.fields['conta'].widget.attrs['placeholder'] = 'Conta'

        self.fields['agencia'].widget.attrs['class'] = 'form-control'
        self.fields['agencia'].widget.attrs['placeholder'] = 'Agência'
        
        self.fields['titular'].widget.attrs['class'] = 'form-control'
        self.fields['titular'].widget.attrs['placeholder'] = 'Titular'

        self.fields['cpf_cnpj'].widget.attrs['class'] = 'form-control'
        self.fields['cpf_cnpj'].widget.attrs['placeholder'] = 'CPF/CNPJ'       

apps/website/views.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.views.generic import RedirectView, View, UpdateView, ListView, DetailView, DeleteView, CreateView
from django.template import RequestContext
from django.http import (JsonResponse, HttpResponse, HttpResponseForbidden, HttpResponseBadRequest, HttpResponseRedirect)
from datetime import datetime, timedelta, date
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import json

from .forms import *
from apps.painel.models import *


class Home(View):
    def get(self, request):
    	publicacoes = Publicacao.objects.all().order_by('-data')[:3]
    	projetos = Projeto.objects.all().order_by('-data')[:6]
    	albuns = Album.objects.all().order_by('-data')[:4]
    	imagens = Imagem.objects.all().order_by('-album__data')

    	galeria = []
    	for album in albuns:
    		for imagem in imagens:
    			if album.pk == imagem.album.pk:
    				galeria.append(imagem)
    				break
    			pass
    		pass
    	pass

    	context = {'publicacoes':publicacoes, 'projetos':projetos, 'galeria':galeria}
    	return render (request, 'index.html', context)



class Sobre(View):
    def get(self, request):
    	context = {}
    	return render (request, 'sobre.html', context) 


class Galeria(View):
	def get(self, request, pk):
		imagens = Imagem.objects.filter(album=pk)
		context = {'imagens':imagens}
		return render(request, 'galeria/galeria.html', context)


class ListaGaleria(View):
	def get(self, request):
		albuns = Album.objects.all().order_by('-data')[:4]
		imagens = Imagem.objects.all().order_by('-album__data')

		galeria = []
		for album in albuns:
			for imagem in imagens:
				if album.pk == imagem.album.pk:
					galeria.append(imagem)
					break
				pass
			pass
			
		context = {'galeria':galeria}
		return render(request, 'galeria/list.html', context)


class Noticia(View):
	def get(self, request, pk):
		publicacao = Publicacao.objects.get(pk=pk)
		context = {'publicacao':publicacao}
		return render(request, 'noticia/noticia.html', context)

class ListaNoticias(View):
	def get(self, request):
		publicacoes = Publicacao.objects.all()
		context = {'publicacoes':publicacoes}
		return render(request, 'noticia/list.html', context)



class Contato(View):
	def get(self, request):
		form = ContatoForm
		telefones = Telefone.objects.all()
		context = {'form':form, 'message':False, 'telefones':telefones}
		return render (request, 'contato.html', context)

	def post(self, request, *args, **kwargs):
		form = ContatoForm(request.POST)
		telefones = Telefone.objects.all()
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
		form = ContatoForm()
		context = {'form':form, 'message':True, 'telefones':telefones}
		return render (request, 'contato.html', context)



class Doacao(View):
	def get(self, request):
		form = DoacaoForm
		context = {'form':form, 'message':False}
		return render (request, 'doacao.html', context)

	def post(self, request, *args, **kwargs):
		form = DoacaoForm(request.POST)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			form = DoacaoForm()
			context = {'form':form, 'message':True}
		else:
			context = {'form':form, 'message':False}
			
		return render (request, 'doacao.html', context)

apps/website/templates/contato.html
{% extends "site/base.html" %} 
{% load staticfiles %}

{% block content %}

<div class="fh5co-hero">
	<div class="fh5co-overlay"></div>
	<div class="fh5co-cover text-center" data-stellar-background-ratio="0.5" style="background-image: url(/static/site/images/cover_bg_2.jpg);">
		<div class="desc animate-box">
			<h2>Para<strong> dúvidas</strong> entre em contato.</h2>
			<span><a class="btn btn-primary btn-lg find-contato" href="#">Contato</a></span>
		</div>
	</div>

</div>

<div id="fh5co-contact" class="animate-box">
	<div class="container">
		{% if message %}
		<div class="row">
			<div class="col-md-12 text-center heading-section">
				<h3>Obrigado pelo contato.</h3>
				<p>
					Retornaremos o mais breve possível. Se precisar entrar em contato {% if telefones %} ligando para {% for telefone in telefones %} <a href="tel:+55{{telefone.get_numero}}">{{telefone}}</a>, {% endfor %} ou {% endif %} envie um email para <a href="mailto:cedroestacao@gmail.com">cedroestacao@gmail.com</a>. 
					<br/>
					Você também pode deixar sujestões ou falar conosco pelo nosso website clicando <a href="{% url 'website:contato' %}">aqui</a>.
				</p>
			</div>
		</div>
		{% endif %}
		<form id="form-contato" class="form-contato" autocomplete="off" method="post" enctype="multipart/form-data" role="form">{% csrf_token %}
			<div class="row">
				<div class="col-md-5">
					<h3 class="section-title">Nosso Endereço</h3>
					<ul class="contact-info">
						<li>
							<i class="icon-location-pin"></i>
							<adress>
								End. Rua Adelino Alves Saldanha, 562, Cedro - Areal - RJ
							</adress>
						</li>
						{% if telefones %}
							<li>
								<i class="icon-phone2"></i>
								{% for telefone in telefones %}
									<a href="tel:+55{{telefone.get_numero}}">{{telefone}}</a><br/>
								{% endfor %}
							</li>
						{% endif %}
						<li>
							<i class="icon-mail"></i>
							<a href="mailto:ong.cedro.areal@gmail.com">ong.cedro.areal@gmail.com</a>
						</li>
						<li>
							<i class="icon-globe2"></i>
							<a href="{% url 'website:home' %}">www.estacaocedro.com.br</a>
						</li>
					</ul>
				</div>
				<div class="col-md-7">
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								{{ form.nome }}
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								{{ form.telefone }}
							</div>
						</div>
						<div class="col-md-12">
							<div class="form-group">
								{{ form.email }}
							</div>
						</div>
						<div class="col-md-12">
							<div class="form-group">
								<textarea name="descricao" class="form-control" id="" cols="30" rows="7" placeholder="Mensagem"></textarea>
							</div>
						</div>
						<div class="col-md-12">
							<div class="form-group">
								<input type="submit" value="Enviar Mensagem" class="btn btn-primary">
							</div>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
<!-- END fh5co-contact -->
<div id="map" class="fh5co-map"></div>
<!-- END map -->

{% endblock %}

{% block javascript %}
<!-- Google Map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCefOgb1ZWqYtj7raVSmN4PL2WkTrc-KyA&sensor=false"></script>
<script src="/static/site/js/google_map.js"></script>
<script type="text/javascript">
$('.form-contato').validate({
	messages: {
        'NOTEMPTY': 'Por favor, preencha este campo.'
    },
    submit: {
        settings: {
			inputContainer : '.form-group',
			errorListClass : 'form-error'
        }
    }
});

$(function(){
	$('.find-contato').click(function(event){
		event.preventDefault()
	    $('html,body').animate({scrollTop: $("#form-contato").offset().top - 200},'slow');
	});
});
</script>
{% endblock %}

apps/website/templates/index.html
{% extends "site/base.html" %} 
{% load staticfiles %}

{% block css %}
	<!-- Custom css -->
	<link rel="stylesheet" href="/static/site/css/custom.css">
{% endblock %}

{% block content %}

<div class="fh5co-hero">
	<div class="fh5co-overlay"></div>
	<div class="fh5co-cover text-center" data-stellar-background-ratio="0.5" style="background-image: url(/static/site/images/foto_0.jpg);">
		<div class="desc animate-box">
			<h2><strong>Ajude uma criança</strong> a  <strong>estudar</strong></h2>
			<span>Faça parte dessa mudança</span>
			<span><a class="btn btn-primary btn-lg" href="{% url 'website:doar' %}">Doe agora</a></span>
		</div>
	</div>
</div>

<!-- end:header-top -->
<div id="fh5co-features">
	<div class="container">
		<div class="row">
			<div class="col-md-4">

				<div class="feature-left">
					<span class="icon">
						<i class="icon-profile-male"></i>
					</span>
					<div class="feature-copy">
						<h3>Torne-se um voluntário</h3>
						<p>Faça parte de nosso grupo tornando-se um voluntário.</p>
						<p><a href="{% url 'website:doar'%}">Leia Mais</a></p>
					</div>
				</div>

			</div>

			<div class="col-md-4">
				<div class="feature-left">
					<span class="icon">
						<i class="icon-happy"></i>
					</span>
					<div class="feature-copy">
						<h3>Acompanhe nossos eventos</h3>
						<p>Ajude-nos a crescer acompanhe nossos eventos  e ajude na divulgação.</p>
						<p><a href="{% url 'website:noticia-lista'%}">Leia Mais</a></p>
					</div>
				</div>

			</div>
			<div class="col-md-4">
				<div class="feature-left">
					<span class="icon">
						<i class="icon-wallet"></i>
					</span>
					<div class="feature-copy">
						<h3>Doações</h3>
						<p>Doe! qualquer quantia auxilia muito nossa causa.</p>
						<p><a href="{% url 'website:doar'%}">Leia Mais</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% if galeria %}
<div id="fh5co-portfolio">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3 text-center heading-section animate-box">
				<h3>Galeria de Fotos</h3>
				<p>Acompanhe nosso trabalho, visite nossa galeria</p>
			</div>
		</div>
		<div class="row row-bottom-padded-md">
			<div class="col-md-12">
				<ul id="fh5co-portfolio-list">
					{% for imagem in galeria %}	
						{% ifchanged imagem.album %}	
							{% if forloop.counter == 1 or forloop.counter == 4 %}
							<li class="two-third animate-box" data-animate-effect="fadeIn" style="background-image: url(/media/{{imagem.imagem}}); ">
							{% else %}
							<li class="one-third animate-box" data-animate-effect="fadeIn" style="background-image: url(/media/{{imagem.imagem}}); ">
							{% endif %}
								<a href="{% url 'website:galeria' imagem.album.pk %}" class="color-3">
									<div class="case-studies-summary">
										<span>{{imagem.album.categoria}}</span>
										<h2>{{imagem.album.titulo}}</h2>
									</div>
								</a>
							</li>
						{% endifchanged %}
					{% endfor %}
				</ul>		
			</div>
		</div>
		<div class="row">
			<div class="col-md-4 col-md-offset-4 text-center animate-box">
				<a href="{% url 'website:galeria-lista' %}" class="btn btn-primary btn-lg">Ver galeria</a>
			</div>
		</div>
	</div>
</div>
{% endif %}


<div id="fh5co-content-section" class="fh5co-section-gray">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
				<h3>Nossa Equipe</h3>
				<p>Conheça melhor nossa equipe e as pessoas que fazem tornaram esta iniciativa possível.</p>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<div class="fh5co-testimonial text-center animate-box">
					<figure>
						<img src="/static/site/images/person_1.jpg" alt="user">
					</figure>
					<blockquote>
						<p>&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;</p>
					</blockquote>
					<span>Jean Doe, XYZ Co.</span>
				</div>
			</div>
			<div class="col-md-4">
				<div class="fh5co-testimonial text-center animate-box">
					<figure>
						<img src="/static/site/images/person_2.jpg" alt="user">
					</figure>
					<blockquote>
						<p>&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;</p>
					</blockquote>
					<span>John Doe, XYZ Co.</span>
				</div>
			</div>
			<div class="col-md-4">
				<div class="fh5co-testimonial text-center animate-box">
					<figure>
						<img src="/static/site/images/person_3.jpg" alt="user">
					</figure>
					<blockquote>
						<p>&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;</p>
					</blockquote>
					<span>John Doe, XYZ Co.</span>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- fh5co-content-section -->
{% if projetos %}
<div id="fh5co-services-section">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
				<h3>Nossos Projetos</h3>
				<p>Conheça nossos projetos e descubra quais são nossos planos para o futuro.</p>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row text-center">
			{% for projeto in projetos %}
				<div class="col-md-4 col-sm-4">
					<div class="services animate-box">
						<span><i class="icon-heart"></i></span>
						<h3>{{projeto.titulo}}</h3>
						<p>{{projeto.descricao|truncatechars:145}}</p>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
</div>
{% endif %}

<!-- END What we do -->

{% if publicacoes %}
<div id="fh5co-blog-section" class="fh5co-section-gray">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
				<h3>Ultimas Notícias</h3>
				<p>
					Acompanhe nossas atividades e os ultimos eventos realizados.
				</p>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row row-bottom-padded-md">
			{% for publicacao in publicacoes %}
			<div class="col-lg-4 col-md-4 col-sm-6">
				<div class="fh5co-blog animate-box">
					<a href="{% url 'website:noticia' publicacao.pk %}">
						<img class="img-responsive img-custom" src="/media/{{publicacao.imagem}}" alt="{{publicacao.titulo}}">
					</a>
					<div class="blog-text">
						<div class="prod-title">
							<h3>
								<a href="{% url 'website:noticia' publicacao.pk %}">{{publicacao.titulo}}</a>
							</h3>
							<span class="posted_by">{{publicacao.data}}</span>
							<p class="publicacao-resumo" title="{{publicacao.resumo}}">
								{{publicacao.resumo|truncatechars:100}}
							</p>
							<p>
								<a href="{% url 'website:noticia' publicacao.pk %}">Leia mais...</a>
							</p>
						</div>
					</div> 
				</div>
			</div>
			{% endfor %}
			<div class="clearfix visible-md-block"></div>
		</div>

		<div class="row">
			<div class="col-md-4 col-md-offset-4 text-center animate-box">
				<a href="{% url 'website:noticia-lista' %}" class="btn btn-primary btn-lg">Ver Mais</a>
			</div>
		</div>

	</div>
</div>
{% endif %}

{% endblock %}

{% block javascript %}{% endblock %}

apps/website/templates/listanoticias.html
{% extends "site/base.html" %} 
{% load staticfiles %}

{% block css %}
	<!-- Custom css -->
	<link rel="stylesheet" href="/static/site/css/custom.css">
{% endblock %}

{% block content %}
	{% if not publicaoes %}
	<div id="fh5co-blog-section" class="fh5co-section-gray">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
					<h3>Conheça nosso trabalho e faça parte</h3>
					<p>Fique por dentro de nossas ultimas atividades.</p>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row row-bottom-padded-md">
				{% for publicacao in publicacoes %}
					<div class="col-lg-4 col-md-4 col-sm-6">
						<div class="fh5co-blog animate-box">
							<a href="{% url 'website:noticia' publicacao.pk %}">
								<img class="img-responsive img-custom" src="/media/{{publicacao.imagem}}" alt="{{publicacao.titulo}}">
							</a>
							<div class="blog-text">
								<div class="prod-title">
									<h3>
										<a href="{% url 'website:noticia' publicacao.pk %}">
											{{publicacao.titulo}}
										</a>
									</h3>
									<span class="posted_by">{{publicacao.data}}</span>
									<p class="publicacao-resumo" title="{{publicacao.resumo}}">
										{{publicacao.resumo|truncatechars:100}}
									</p>
									<p><a href="{% url 'website:noticia' publicacao.pk %}">Leia mais...</a></p>
								</div>
							</div> 
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
	{% else %}
	<div id="fh5co-feature-product" class="fh5co-section-gray">
		<div class="container">

			<div class="row">
				<div class="col-md-12 text-center heading-section">
					<h3>
						Infelismente parece que não temos nenhuma notícia recente.
						Volte mais tarde e fique por dentro de nossas ultimas atividades.
					</h3>
					<p><b>Associação de transformação social (Estação cedro) – ONG</b></p>
				</div>
			</div>

		</div>
	</div>
	{% endif %}
{% endblock %}

{% block javascript %}{% endblock %}