apps/painel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from apps.painel import views 

urlpatterns = [
	url(r'^$', login_required(views.Home.as_view()), name='home'),
    url(r'^login/$', views.Login.as_view(), name='login'),
    url(r'^logout/$', views.Logout.as_view(), name='logout'),

    # URLS USUARIO
    url(r'^usuario/$', login_required(views.UsuarioList.as_view()), name='usuario-listar'),
    url(r'^usuario/cadastrar/$', login_required(views.UsuarioRegister.as_view()), name='usuario-cadastrar'),
    url(r'^usuario/deletar/(?P<pk>\d+)/$', login_required(views.UsuarioDelete.as_view()), name='usuario-deletar'),
    url(r'^usuario/senha/$', login_required(views.UsuarioChangePassword.as_view()), name='usuario-senha'),

	# URLS PUBLICAÇÃO
	url(r'^publicacao/$', login_required(views.PublicacaoList.as_view()), name='publicacao-listar'),
    url(r'^publicacao/cadastrar/$', login_required(views.PublicacaoRegister.as_view()), name='publicacao-cadastrar'),
    url(r'^publicacao/editar/(?P<pk>\d+)/$', login_required(views.PublicacaoEdit.as_view()), name='publicacao-editar'),
    url(r'^publicacao/deletar/(?P<pk>\d+)/$', login_required(views.PublicacaoDelete.as_view()), name='publicacao-deletar'),

    # URLS CONTATO
    url(r'^mensagem/$', views.ContatoList.as_view(), name='contato-listar'),
    url(r'^mensagem/visualizar/(?P<pk>\d+)/$', login_required(views.ContatoDetail.as_view()), name='contato-detalhes'),
    url(r'^mensagem/deletar/(?P<pk>\d+)/$', login_required(views.ContatoDelete.as_view()), name='contato-deletar'),

    # URLS DOACAO
    url(r'^doacoes/$', views.DoacaoList.as_view(), name='doacao-listar'),
    url(r'^doacoes/visualizar/(?P<pk>\d+)/$', login_required(views.DoacaoDetail.as_view()), name='doacao-detalhes'),
    url(r'^doacoes/deletar/(?P<pk>\d+)/$', login_required(views.DoacaoDelete.as_view()), name='doacao-deletar'),

    # URLS PROJETO
    url(r'^projeto/$', login_required(views.ProjetoList.as_view()), name='projeto-listar'),
    url(r'^projeto/cadastrar/$', login_required(views.ProjetoRegister.as_view()), name='projeto-cadastrar'),
    url(r'^projeto/editar/(?P<pk>\d+)/$', login_required(views.ProjetoEdit.as_view()), name='projeto-editar'),
    url(r'^projeto/deletar/(?P<pk>\d+)/$', login_required(views.ProjetoDelete.as_view()), name='projeto-deletar'),

    # URLS ALBUM
    url(r'^album/$', login_required(views.AlbumList.as_view()), name='album-listar'),
    url(r'^album/cadastrar/$', login_required(views.AlbumRegister.as_view()), name='album-cadastrar'),
    url(r'^album/editar/(?P<pk>\d+)/$', login_required(views.AlbumEdit.as_view()), name='album-editar'),
    url(r'^album/delete/(?P<pk>\d+)/$', login_required(views.AlbumDelete.as_view()), name='album-deletar'),
    url(r'^foto/delete/(?P<pk>\d+)/$', login_required(views.FotoDelete.as_view()), name='foto-deletar'),

    # URLS ALBUM
    url(r'^telefone/$', login_required(views.TelefoneList.as_view()), name='telefone-listar'),
    url(r'^telefone/cadastrar/$', login_required(views.TelefoneRegister.as_view()), name='telefone-cadastrar'),
    url(r'^telefone/editar/(?P<pk>\d+)/$', login_required(views.TelefoneEdit.as_view()), name='telefone-editar'),
    url(r'^telefone/delete/(?P<pk>\d+)/$', login_required(views.TelefoneDelete.as_view()), name='telefone-deletar'),
]

estacaocedro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap, index
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf import settings
from .sitemaps import *

sitemaps = {
	'static':StaticViewSitemap,
	'noticia':NoticiaSitemap,
	'galeria':GaleriaSitemap
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sitemap\.xml$', index, {'sitemaps':sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file"),
    url(r'^', include('apps.website.urls', namespace='website')),
    url(r'^painel/', include('apps.painel.urls', namespace='painel')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/painel/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.sitemaps import ping_google
import re

class Publicacao(models.Model):
	id = models.AutoField(primary_key=True)
	usuario = models.ForeignKey(User)
	titulo = models.CharField('Título', max_length=50, unique=True)
	resumo = models.TextField('Breve Resumo')
	imagem = models.ImageField('Imagem')
	conteudo = models.TextField('Conteúdo')
	data = models.DateTimeField('Data de Publicação', default=timezone.now)

	def __str__(self):
	    return str(self.titulo)

class Projeto(models.Model):
	id = models.AutoField(primary_key=True)
	usuario = models.ForeignKey(User)
	titulo = models.CharField('Título', max_length=50, unique=True)
	descricao = models.TextField('Descrição')
	data = models.DateTimeField('Data de Publicação', default=timezone.now)

	def __str__(self):
	    return str(self.titulo)

	def save(self, force_insert=False, force_update=False):
		super(Projeto, self).save(force_insert, force_update)
		try:
			pring_google()
		except Exception:
			pass


class Album(models.Model):
	usuario = models.ForeignKey(User)
	titulo = models.CharField('Título', max_length=50, unique=True)
	categoria = models.CharField('Categoria', max_length=50, blank=True)
	data_album = models.DateField('Data do Evento')
	data = models.DateTimeField('Data de Criação', default=timezone.now)

	def __str__(self):
	    return str(self.titulo)

	def save(self, force_insert=False, force_update=False):
		super(Album, self).save(force_insert, force_update)
		try:
			pring_google()
		except Exception:
			pass


class Imagem(models.Model):
	album = models.ForeignKey(Album)
	imagem = models.ImageField('Foto')

	def __str__(self):
	    return str(self.imagem)

	def save(self, force_insert=False, force_update=False):
		super(Imagem, self).save(force_insert, force_update)
		try:
			pring_google()
		except Exception:
			pass

class Telefone(models.Model):
	numero = models.CharField('Número', max_length=50, unique=True)
	usuario = models.ForeignKey(User)
	data = models.DateTimeField('Data de Criação', default=timezone.now)

	def __str__(self):
	    return str(self.numero)

	def get_numero(self):
		return re.sub('[^0-9]', '', self.numero)

apps/painel/views.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.views.generic import RedirectView, View, UpdateView, ListView, DetailView, DeleteView, CreateView
from django.template import RequestContext
from django.http import (JsonResponse, HttpResponse, HttpResponseForbidden, HttpResponseBadRequest, HttpResponseRedirect)
from datetime import datetime, timedelta, date
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User as Usuario
from django.contrib.auth import update_session_auth_hash
from django.utils import timezone
import json

from apps.website.models import *
from apps.website.forms import *
from .models import *
from .forms import *


class Home(View):
    def get(self, request):
        return render (request, 'core/index.html')



class Login(View):
    def get(self, request):
        form = LoginForm()
        context = {'form':form}
        return render (request, 'registration/login.html', context)

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        context = {'form':form}
        if form.is_valid():
            user = authenticate(username=form.cleaned_data.get("usuario"), password=form.cleaned_data.get("password"))
            login(request, user)
            next = request.GET.get('next')
            if next:
                return redirect(next)
        return render (request, 'registration/login.html', context)

class Logout(View):
    def get(self, request):
        logout(request)
        return redirect(reverse_lazy("painel:login")+ '?next=/painel/')



class UsuarioRegister(View):
    def get(self, request):
        if not request.user.is_staff:
            return redirect(reverse_lazy("painel:home"))
        form = UsuarioForm()
        context = {'form':form}
        return render (request, 'usuario/register.html', context)

    def post(self, request, *args, **kwargs):
        form = UsuarioForm(request.POST)
        context = {'form':form}
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            return redirect(reverse_lazy("painel:usuario-listar"))
        else:
            return render (request, 'usuario/register.html', context)

class UsuarioList(View):
    def get(self, request):
        obj_list = Usuario.objects.all().exclude(pk=request.user.pk).order_by('-date_joined')

        paginator = Paginator(obj_list, 25)
        page = request.GET.get('page')
        try:
            usuarios = paginator.page(page)
        except PageNotAnInteger:
            usuarios = paginator.page(1)
        except EmptyPage:
            usuarios = paginator.page(paginator.num_pages)
        context = {'usuarios': usuarios}
        return render(request, 'usuario/list.html', context)

class UsuarioDelete(View):
    def get(self, request, pk):
        usuario = Usuario.objects.get(pk=pk).delete()
        return redirect(reverse_lazy("painel:usuario-listar"))

class UsuarioChangePassword(View):
    def get(self, request):
        form = ChangePasswordForm(request.user)
        context = {'form':form}
        return render (request, 'usuario/changepassword.html', context)
    def post(self, request, *args, **kwargs):
        form = ChangePasswordForm(request.user, data=request.POST)
        context = {'form':form}
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse_lazy("painel:home"))
        else:
            return render (request, 'usuario/changepassword.html', context)        


class PublicacaoRegister(View):
    def get(self, request):
        form = PublicacaoForm()
        context = {'form':form}
        return render (request, 'publicacao/register.html', context)

    def post(self, request, *args, **kwargs):
        form = PublicacaoForm(request.POST, request.FILES)
        context = {'form':form}
        if form.is_valid():
            obj = form.save(commit=False)
            obj.usuario = request.user
            obj.save()
            return redirect(reverse_lazy("painel:publicacao-listar"))
        else:
            return render (request, 'publicacao/register.html', context)

class PublicacaoEdit(View):
    def get(self, request, pk):
        publicacao = Publicacao.objects.get(pk=pk)
        form = PublicacaoForm(instance=publicacao)
        context = {'form':form, 'publicacao':publicacao}
        return render (request, 'publicacao/edit.html', context)

    def post(self, request, pk, *args, **kwargs):
        publicacao = Publicacao.objects.get(pk=pk)
        form = PublicacaoForm(request.POST, request.FILES, instance=publicacao)
        context = {'form':form}
        if form.is_valid():
            obj = form.save(commit=False)
            obj.usuario = request.user
            obj.save()
            return redirect(reverse_lazy("painel:publicacao-listar"))
        else:
            return render (request, 'publicacao/edit.html', context)

class PublicacaoList(View):
    def get(self, request):
        publicacoes = Publicacao.objects.all()
        context = {'publicacoes': publicacoes}
        return render(request, 'publicacao/list.html', context)

class PublicacaoDelete(View):
    def get(self, request, pk):
        publicacao = Publicacao.objects.get(pk=pk).delete()
        return redirect(reverse_lazy("painel:publicacao-listar"))



class ContatoList(View):
    def get(self, request):
        obj_list = Contato.objects.all().order_by('data')

        paginator = Paginator(obj_list, 25)
        page = request.GET.get('page')
        try:
            contatos = paginator.page(page)
        except PageNotAnInteger:
            contatos = paginator.page(1)
        except EmptyPage:
            contatos = paginator.page(paginator.num_pages)
        context = {'contatos': contatos}
        return render(request, 'contato/list.html', context)

class ContatoDetail(View):
    def get(self, request, pk):
        contato = Contato.objects.get(pk=pk)
        contato.is_visualizada = True
        contato.save()
        form = ContatoForm(instance=contato)
        form.fields['nome'].widget.attrs['disabled'] = True
        form.fields['telefone'].widget.attrs['disabled'] = True
        form.fields['email'].widget.attrs['disabled'] = True
        form.fields['descricao'].widget.attrs['disabled'] = True

        context = {'form':form, 'contato':pk}
        return render (request, 'contato/detail.html', context)

class ContatoDelete(View):
    def get(self, request, pk):
        contato = Contato.objects.get(pk=pk).delete()
        return redirect(reverse_lazy("painel:contato-listar"))



class DoacaoList(View):
    def get(self, request):
        obj_list = Doacao.objects.all().order_by('-data')

        paginator = Paginator(obj_list, 25)
        page = request.GET.get('page')
        try:
            doacoes = paginator.page(page)
        except PageNotAnInteger:
            doacoes = paginator.page(1)
        except EmptyPage:
            doacoes = paginator.page(paginator.num_pages)
        context = {'doacoes': doacoes}
        return render(request, 'doacao/list.html', context)

class DoacaoDetail(View):
    def get(self, request, pk):
        doacao = Doacao.objects.get(pk=pk)
        doacao.is_visualizada = True
        doacao.save()
        form = DoacaoForm(instance=doacao)
        form.fields['nome'].widget.attrs['disabled'] = True
        form.fields['rg'].widget.attrs['disabled'] = True
        form.fields['cpf'].widget.attrs['disabled'] = True
        form.fields['email'].widget.attrs['disabled'] = True
        form.fields['nome'].widget.attrs['disabled'] = True
        form.fields['telefone'].widget.attrs['disabled'] = True
        form.fields['celular'].widget.attrs['disabled'] = True
        form.fields['cep'].widget.attrs['disabled'] = True
        form.fields['rua'].widget.attrs['disabled'] = True
        form.fields['bairro'].widget.attrs['disabled'] = True
        form.fields['cidade'].widget.attrs['disabled'] = True
        form.fields['estado'].widget.attrs['disabled'] = True
        form.fields['valor'].widget.attrs['disabled'] = True
        form.fields['modalidade'].widget.attrs['disabled'] = True
        form.fields['banco'].widget.attrs['disabled'] = True
        form.fields['conta'].widget.attrs['disabled'] = True
        form.fields['agencia'].widget.attrs['disabled'] = True
        form.fields['titular'].widget.attrs['disabled'] = True
        form.fields['cpf_cnpj'].widget.attrs['disabled'] = True

        context = {'form':form, 'doacao':pk}
        return render (request, 'doacao/detail.html', context)

class DoacaoDelete(View):
    def get(self, request, pk):
        doacao = Doacao.objects.get(pk=pk).delete()
        return redirect(reverse_lazy("painel:doacao-listar"))
    


class ProjetoRegister(View):
    def get(self, request):
        form = ProjetoForm()
        context = {'form':form}
        return render (request, 'projeto/register.html', context)

    def post(self, request):
        form = ProjetoForm(request.POST, request.FILES)
        context = {'form':form}
        if form.is_valid():
            obj = form.save(commit=False)
            obj.usuario = request.user
            obj.save()
            return redirect(reverse_lazy("painel:projeto-listar"))
        else:
            return render (request, 'projeto/register.html', context)

class ProjetoEdit(View):
    def get(self, request, pk):
        projeto = Projeto.objects.get(pk=pk)
        form = ProjetoForm(instance=projeto)
        context = {'form':form, 'projeto':projeto}
        return render (request, 'projeto/edit.html', context)

    def post(self, request, pk):
        projeto = Projeto.objects.get(pk=pk)

apps/painel/templates/telefone/edit.html
{% extends 'painel/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="/static/painel/build/css/separate/pages/others.min.css">
<link rel="stylesheet" href="/static/painel/build/css/separate/vendor/bootstrap-select/bootstrap-select.min.css">
<link rel="stylesheet" href="/static/painel/build/css/separate/vendor/select2.min.css">
{% endblock %}
{% block content %}
<form id="form-telefone" class="form-telefone" name="form_telefone"  method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="box-typical box-typical-padding">
		<div class="row">
			<div class="col-lg-2 col-sm-4 text-center">
				<h2 class="m-t-lg"><i class="text-muted font-icon font-icon-question"></i></h2>
				<h5 class="m-b semibold">Editando um Telefone</h5>
				<p>
					Você poderá editar seus telefones ao preencher este formulário.
				</p>
			</div>
			<div class="col-lg-10 col-sm-8">

				<h5 class="m-t-lg with-border">Editar Telefone</h5>

				<div class="row">
					<div class="col-lg-12">
						<fieldset class="form-group">
							<label for="{{form.numero.id_for_label}}" class="col-sm2 form-label semibold">
								{{ form.numero.label_tag }}
							</label>
							<div class="col-sm10">
								<p class="form-control-static">
									{{ form.numero }}
								</p>
								<small class="text-muted">{{ form.numero.errors }}</small>
							</div>
						</fieldset>
					</div>
				</div>

				<div class="row">
					<div class="col-lg-12">
						<div class="form-group">
							<button class="btn btn-save" type="submit">Salvar Telefone</button>
							<div class="pull-right">
								<a class="btn btn-secondary-outline" href="{% url 'painel:telefone-listar' %}">Cancelar</a>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
</form>
{% endblock %}
{% block javascript %}>
<script src="/static/painel/build/js/lib/bootstrap-select/bootstrap-select.min.js"></script>
<script src="/static/painel/build/js/lib/select2/select2.full.min.js"></script>
<script src="/static/painel/build/js/lib/html5-form-validation/jquery.validation.min.js"></script>
<script>
	$(function() {
	    $('.form-telefone').validate({
	        submit : {
	            settings : {
	                inputContainer : '.form-group',
	                errorListClass : 'form-tooltip-error'
	            },
	        }
	    });

	});
</script>
{% endblock %}

apps/painel/templates/telefone/list.html
{% extends 'painel/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="/static/painel/build/css/separate/pages/others.min.css">
<link rel="stylesheet" href="/static/painel/build/css/lib/bootstrap-table/bootstrap-table.min.css">
{% endblock %}
{% block content %}
{% if telefones %}
<div class="box-typical box-typical-full-height" style="min-height: 444px;">
	<section class="box-typical">
		<div id="toolbar">
			<div class="bootstrap-table-header">
				Telefones
			</div>
		</div>
		<div class="table-responsive">
			<table id="table"
			class="table table-striped"
			data-toolbar="#toolbar"
			data-search="true"
			data-show-refresh="true"
			data-show-toggle="true"
			data-show-columns="true"
			data-show-export="true"
			data-detail-view="false"
			data-detail-formatter="detailFormatter"
			data-minimum-count-columns="2"
			data-show-pagination-switch="true"
			data-pagination="false"
			data-id-field="id"
			data-page-list="[10, 25, 50, 100, ALL]"
			data-show-footer="false"
			data-response-handler="responseHandler">
				<thead>
					<tr>
						<th data-field="nome" data-sortable="true">Número</th>
						<th data-field="data" data-sortable="true">Data</th>
						<th data-field="criado por" data-sortable="true">Criado por</th>
						<th data-field="" data-sortable="true">Opções</th>
					</tr>
				</thead>
				<tbody>
					{% for telefone in telefones %}
						<tr>
							<td>{{ telefone.numero }} </td>
							<td>{{ telefone.data }}</td>
							<td>{{ telefone.usuario }}</td>
							<td style="text-align: center;">
			                  <a href="{% url 'painel:telefone-editar' telefone.pk %}" class="like">
			                    <i class="font-icon font-icon-pencil"></i>
			                  </a>
			                  <a href="{% url 'painel:telefone-deletar' telefone.pk %}" class="like">
			                    <i class="font-icon font-icon-trash"></i>
			                  </a>				                  
			                </td> 
						</tr>
					{% endfor %}
        		</tbody>
			</table>
		</div>
	</section>
	<nav aria-label="Page navigation example">
	    <ul class="pagination">
	      {% if telefones.has_previous %}
	        <li class="page-item">
	          <a class="page-link" href="?page={{ telefones.previous_page_number }}" aria-label="Previous">
	            <span aria-hidden="true">&laquo;</span>
	            <span class="sr-only">Anterior</span>
	          </a>
	        </li>
	      {% else %}
	        <li class="page-item disabled">
	          <a class="page-link" href="" aria-label="Previous">
	            <span aria-hidden="true">&laquo;</span>
	            <span class="sr-only">Anterior</span>
	          </a>
	        </li>
	      {% endif %}
	      
	      {% for page in telefones.paginator.page_range%}
	        <li class="page-item {% if page == telefones.number %} active {% endif %}"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
	      {% endfor %}

	      {% if telefones.has_next %}
	        <li class="page-item">
	          <a class="page-link" href="?page={{ telefones.next_page_number }}" aria-label="Next">
	            <span aria-hidden="true">&raquo;</span>
	            <span class="sr-only">Proximo</span>
	          </a>
	        </li>
	      {% else %}
	        <li class="page-item disabled">
	          <a class="page-link" href="" aria-label="Next">
	            <span aria-hidden="true">&raquo;</span>
	            <span class="sr-only">Proximo</span>
	          </a>
	        </li>
	      {% endif %}
	    </ul>
    </nav>
</div>
{% else %}
<div class="box-typical box-typical-full-height" style="min-height: 444px;">
	<div class="add-model-screen tbl" style="height: 444px;">
		<div class="add-model-screen-in">
			<div class="add-model-screen-user">
				<i class="font-icon font-icon-user"></i>
			</div>
			<h2>Aqui serão listados seus telefones</h2>
			<p class="lead color-blue-grey-lighter">
				Parece que você ainda não tem nenhum
				<br>
				<b>Telefone</b> cadastrado.
			</p>
			<!--<a href="" class="btn"></a>-->
		</div>
	</div>
</div><!--.box-typical-->
{% endif %}
{% endblock %}
{% block javascript %}
<script src="/static/painel/build/js/lib/bootstrap-table/bootstrap-table.js"></script>
<script src="/static/painel/build/js/lib/bootstrap-table/bootstrap-table-init.js"></script>
{% endblock %}

apps/painel/templates/telefone/register.html
{% extends 'painel/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="/static/painel/build/css/separate/pages/others.min.css">
<link rel="stylesheet" href="/static/painel/build/css/separate/vendor/bootstrap-select/bootstrap-select.min.css">
<link rel="stylesheet" href="/static/painel/build/css/separate/vendor/select2.min.css">
{% endblock %}
{% block content %}
<form id="form-telefone" class="form-telefone" name="form_telefone"  method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="box-typical box-typical-padding">
		<div class="row">
			<div class="col-lg-2 col-sm-4 text-center">
				<h2 class="m-t-lg"><i class="text-muted font-icon font-icon-question"></i></h2>
				<h5 class="m-b semibold">Criando um Telefone</h5>
				<p>
					Você poderá criar novas telefones ao preencher este formulário.
				</p>
			</div>
			<div class="col-lg-10 col-sm-8">

				<h5 class="m-t-lg with-border">Novo Telefone</h5>

				<div class="row">
					<div class="col-lg-12">
						<fieldset class="form-group">
							<label for="{{form.numero.id_for_label}}" class="col-sm2 form-label semibold">
								{{ form.numero.label_tag }}
							</label>
							<div class="col-sm10">
								<p class="form-control-static">
									{{ form.numero }}
								</p>
								<small class="text-muted">{{ form.numero.errors }}</small>
							</div>
						</fieldset>
					</div>
				</div>

				<div class="row">
					<div class="col-lg-12">
						<div class="form-group">
							<button class="btn btn-save" type="submit">Salvar Telefone</button>
							<div class="pull-right">
								<a class="btn btn-secondary-outline" href="{% url 'painel:telefone-listar' %}">Cancelar</a>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
</form>
{% endblock %}
{% block javascript %}>
<script src="/static/painel/build/js/lib/bootstrap-select/bootstrap-select.min.js"></script>
<script src="/static/painel/build/js/lib/select2/select2.full.min.js"></script>
<script src="/static/painel/build/js/lib/html5-form-validation/jquery.validation.min.js"></script>
<script>
	$(function() {
	    $('.form-telefone').validate({
	        submit : {
	            settings : {
	                inputContainer : '.form-group',
	                errorListClass : 'form-tooltip-error'
	            },
	        }
	    });

	});
</script>
{% endblock %}